FROM nginx:1.25-alpine

COPY index.html        /usr/share/nginx/html/
COPY instructions.html /usr/share/nginx/html/
COPY contacts.html     /usr/share/nginx/html/
COPY css               /usr/share/nginx/html/css
COPY js                /usr/share/nginx/html/js

EXPOSE 80
