play.http.secret.key = "changeme-for-production-use-256-bits-secret!"
#play.http.secret.key = "changeme-for-production"


# Database
db.default.driver   = org.postgresql.Driver
db.default.url      = "jdbc:postgresql://"${?DB_HOST}":"${?DB_PORT}"/"${?DB_NAME}
db.default.username = ${?DB_USER}
db.default.password = ${?DB_PASSWORD}

# Anorm uses default db pool
play.db.pool = "hikaricp"

# CORS – allow all origins (frontend served on port 80)
play.filters.enabled += "play.filters.cors.CORSFilter"
play.filters.cors {
  allowedOrigins    = null
  allowedHttpMethods = ["GET", "POST", "OPTIONS"]
  allowedHttpHeaders = null
}

# MQTT
mqtt {
  broker = "tcp://localhost:1883"
  broker = "tcp://"${?MQTT_BROKER}":"${?MQTT_PORT}
  topic  = "mqtt_telemetry"
  topic  = ${?MQTT_TOPIC}
}

play.modules.enabled += "modules.AppModule"
